name: Deploy
on: [push]

jobs:
  build:
    name: Lint, Test and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: .github/deploy/scripts/lint_test_build.sh
      - uses: actions/upload-artifact@v2
        with:
          name: build.zip
          path: build.zip

  deploy:
    name: Deploy the NextJS Static Bundle
    runs-on: ubuntu-latest
    needs: build
    env:
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      AWS_DEFAULT_REGION: ap-southeast-2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/download-artifact@v2
        with:
          name: build.zip
      - run: .github/deploy/scripts/setBranch.sh
      - run: .github/deploy/scripts/deploy.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
